const uuid = require('uuid');
module.exports = [
    // {
    //     Id: uuid.v4(),
    //     projectName: "Port PM Dashboard",
    //     projectDesc: "PM Dashboard",
    //     clientName: "MPA",
    //     totalBudget: 110000,
    //     startDate: "6/27/2016",
    //     endDate: "7/30/2018",
    //     projectManager: "Sides",
    //     overheadRate: "46.5%",
    //     fixedorTM: "T&M",
    //     clientType: "State",
    //     contactName: "Carl Henderson",
    //     email: "chenderson2@marylandports.com",
    //     phone: "410 385-4821",
    // },
    // {
    //     Id: uuid.v4(),
    //     projectName: "MPA 360 Degree Imagery",
    //     projectDesc: "Collect imagery",
    //     clientName: "MPA",
    //     totalBudget: 24000,
    //     startDate: "12/13/2017",
    //     endDate: "12/31/2018",
    //     projectManager: "Sides",
    //     overheadRate: "46.5%",
    //     fixedorTM: "T&M",
    //     clientType: "State",
    //     contactName: "Carl Henderson",
    //     email: "chenderson2@marylandports.com",
    //     phone: "410 385-4821",
    // },
    {
        Id: uuid.v4(),
        projectName: "Timely Warnings",
        projectDesc: "Timely Warning notification tool",
        clientName: "TU Police",
        totalBudget: 21734.67,
        startDate: "7/1/2017",
        endDate: "6/30/2018",
        projectManager: "Sides",
        overheadRate: "0",
        fixedorTM: "T&M",
        clientType: "TU",
        contactName: "Joe Herring",
        email: "cherring@towson.edu",
        phone: "410 704-5913",
        subcontractor:"0"
    },
    {
        Id: uuid.v4(),
        projectName: "Sea Grant",
        projectDesc: "Stormwater BMP reporting",
        clientName: "UM Sea Grant Extension",
        totalBudget: 90318.34,
        startDate: "6/6/2018",
        endDate: "12/31/2018",
        projectManager: "Sides",
        overheadRate: "46.5%",
        fixedorTM: "Fixed",
        clientType: "State",
        contactName: "Jackie Takacs",
        email: "takacs@umsg.umd.edu",
        phone: "240 393-6508",
        subcontractor:"0"
    },
    {
        Id: uuid.v4(),
        projectName: "Low Birth Weight Mapping",
        projectDesc: "Indicator mapping",
        clientName: "Abilities Network",
        totalBudget: 10000,
        startDate: "6/8/2018",
        endDate: "12/31/2018",
        projectManager: "Sides",
        overheadRate: "46.5%",
        fixedorTM: "Fixed",
        clientType: "Non-profit",
        contactName: "Tomeaka Jupiter",
        email: "tjupiter@abilitiesnetwork.org",
        phone: "410 828-7700",
        subcontractor:"0"
    },
    {
        Id: uuid.v4(),
        projectName: "Entreprenurial Ecosystem Dashboard",
        projectDesc: "Entreprenuership Dashboard",
        clientName: "UM System",
        totalBudget: 20000,
        startDate: "4/15/2018",
        endDate: "3/30/2019",
        projectManager: "Sides",
        overheadRate: "0",
        fixedorTM: "Fixed",
        clientType: "State",
        contactName: "Tom Sadowski",
        email: "tsadowski@usmd.edu",
        phone: "410 688-0013",
        subcontractor:"0"
    },
];